### PR TITLE
Add docker-compose.yml file and instructions

### PR DESCRIPTION
**Pull request by NicolasCARPi**
I think it's much easier to have a docker-compose.yml file that is easily editable instead of multi-line docker run commands. So I added one with the instructions in the README.

### CODE REVIEW

**Comment by FlorianRhiem** [comment]
Thank you for the pull request!

**Comment by NicolasCARPi** [comment]
> Thank you for the pull request!

You're welcome :)

Note that it might be good to also have a `:latest` tag in docker hub so the given commands/config can point to that and always be correct. Now if you release a new version you'll need to edit the readme and docker-compose.yml, which is not ideal.

**Comment by FlorianRhiem** [comment]
There are several other locations for updating the version, I usually do this in a seperate release branch. The reason I'm not using `latest` is that it could lead to a version upgrade happening unintentionally. While we do plenty of testing and review before merging changes into `develop` and have the `develop` branch running in a testing and development installation, I still want administrators to make backups before upgrading (and therefore possibly applying database schema migrations).

**Comment by NicolasCARPi** [comment]
I mean not using `latest` in your prod config is the correct thing to do (pinning a version), the idea was to reduce the version string repetition all over the place, using `latest` and recommending to pin the version for prod.

Anyway, that's just my 2 cents, if you have a detailed release process that takes care of updating it in all places, no problem with keeping it like that :) (it just makes diffs messier)

And even if it's not in the doc, having a `latest` tag on docker hub is kinda standard (unless of course you absolutely don't want anyone to use the `latest` tag for the reasons you mentioned, which seems perfectly valid).

> I still want administrators to make backups before upgrading (and therefore possibly applying database schema migrations).

This is unrelated. Here is how I approach this problem:

* the `latest` tag points to the latest stable version (and one can also use a specific version tag of course)
* when the container is upgraded, the code checks if the db schema is correct or if it needs an upgrade
* if an upgrade is needed, display a text to the user pointing to the documentation to run the upgrade
* the upgrade tool (basically a bash script) proposes to the user to make a backup before upgrading the containers
* anyway the backups should already be daily and automated

**Pull request merged**
