### PR TITLE
Add note about dev setup with docker

### PR DESCRIPTION
**Pull request by NicolasCARPi**

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Yes you're correct. In fact in my mind using docker automatically assumes using docker-compose because running commands directly seems barbaric to me!! :p 

I still think it's necessary to include it because you can never have enough documentation and assuming users will "figure things out by themselves" doesn't sound like a very developer friendly approach, even if I agree it didn't take me long to figure it out, but I'm very familiar with the whole thing and thus not necessarily representative of the potential dev userbase.

I'll push some commits later and try and include what you mention about flask debug and the demo script.

**Comment by FlorianRhiem** [comment]
I'm only semi-barbaric then, as I usually run those Docker commands from Makefiles. ;)

My line of thinking was that users who need the instructions should follow the instructions and workflow provided. But yes, a Docker-based alternative won't hurt, as long as it includes enough instructions/steps to be useful. Thanks!

**Comment by jheinen** [comment]
… “semi-barbaric," then what do you call people who write little (or hardly any) documentation?

**Comment by NicolasCARPi** [comment]
I pushed a commit addressing the comments, let me know what you think. :)

**Comment by NicolasCARPi** [comment]
As a side note, I think it would be good to have a `--force` flag on the demo script so it can overwrite the db directly, even if it's not empty (by emptying first of course).

**Comment by FlorianRhiem** [comment]
That is currently part of demo.py, along with the auto login, etc., but sure it could be part of the `set_up_demo` script if a `--force` flag was provided.

**Pull request merged**
